### ISSUE TITLE
Orders list and lineitems list UI problems

### ISSUE THREAD

**Issue by EugeneOkhriemnko** [VirtoCommerce/vc-module-order#17]
Useless pagination (not working)
![image](https://user-images.githubusercontent.com/1429226/30493019-ef4b7570-9a42-11e7-80d8-fdd91d79c2fb.png)

Style problem
![img_15092017_182203_0](https://user-images.githubusercontent.com/1429226/30493098-34c47f0c-9a43-11e7-8aee-b36de4eef739.png)

**Comment by megafreeman** [comment]
There is not required pagination in line items list because all line items come with order info.
Style problem is solved by increasing the width of the blade.
![image](https://user-images.githubusercontent.com/7536694/30706782-c9085a52-9ef9-11e7-97d6-fa5bb2fe4487.png)

[Commit link](https://github.com/VirtoCommerce/vc-module-order/commit/ed6090026ec6276cbd4a62b819310ea9eb37137f)
