### ISSUE TITLE
Remove hard-coded 'Contact' member type to type taken from the real member object

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-order#67]
https://github.com/VirtoCommerce/vc-module-order/blob/master/VirtoCommerce.OrderModule.Web/Scripts/blades/customerOrder-detail.js#L37
Need to load member object first and use it real type for view resolving

**Comment by Andrew-Orlov** [comment]
https://github.com/VirtoCommerce/vc-module-order/pull/73

**Comment by yecli** [comment]
Released in [v2.17.22](https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.22).

**Comment by artem-dudarev** [comment]
Nothing has changed. There is still hardcoded member type 'Contact':
https://github.com/VirtoCommerce/vc-module-order/blob/master/VirtoCommerce.OrderModule.Web/Scripts/blades/customerOrder-detail.js#L57

**Comment by yecli** [comment]
@artem-dudarev As you can see, it was hardcoded type 'Contact' for all members in [line 37](https://github.com/VirtoCommerce/vc-module-order/pull/73/files#diff-d10a1da13900e7441f06891c6723425dL37). 
Now, if we have real member with given id - Contact, Organization, etc. for the order owner - we use its type. It is the case where we could get and removed hardcoded type. 
Otherwise (means there is no corresponding member, so there is no possibility to get memberType from member) - we are using default 'Contact' type and get user from security accounts API.

**Comment by artem-dudarev** [comment]
The problem is that you never load the real member. Order.CustomerId is a UserId and `members.get({ id: blade.customerOrder.customerId }` on line 53 will never find any member.
You should load an account, like on line 55, and AFTER that load a member by account.memberId.

**Comment by yecli** [comment]
I see.
It worked when I checked because for the users defined in sample database User.id == member.id.
![image](https://user-images.githubusercontent.com/15610352/54806170-0d66e600-4c9b-11e9-8a60-0b7d318c4c11.png)
Will rework this task.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.24
